import "./globals.css";

import type { Metadata } from "next";
import Script from "next/script";
import { Suspense } from "react";
import { BarLoader } from "react-spinners";

import { AuthContextProvider } from "@/context/AuthContext";

import RQProvider from "./_component/RQProvider";
import TokenLoginComponent from "./_component/TokenLoginComponent";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Balance Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script src="https://cdn.swygbro.com/public/widget/swyg-widget.js" />
      <body>
        <RQProvider>
          <AuthContextProvider>
            <Suspense
              fallback={
                <div className={styles.spinnerWrapper}>
                  <BarLoader color="#36d7b7" />
                </div>
              }
            >
              <TokenLoginComponent />
              <div className="root_container">{children}</div>
            </Suspense>
          </AuthContextProvider>
        </RQProvider>
        <div id="portal" />
      </body>
    </html>
  );
}
